### ISSUE TITLE
Conversations need owners

### ISSUE THREAD

**Issue by Entryist** [getZION/relay#102]
The [refactored `Conversation` model](https://github.com/getZION/relay/blob/3366ec85225a20907777f16b4e056bf1212f5903/api/api.go#L24) is missing an association with a User.

Need to add a `UserDid` field similar to what `Comment` has.

Can tie this into issue #86, setting the UserDid to the request's authorized user.

**Comment by chrishein3** [comment]
**you need to clear `conversations` table before deploy the project.** I've add some constraint into database too.
