### ISSUE TITLE
Add endpoint for checking whether a username exists

### ISSUE THREAD

**Issue by Entryist** [getZION/relay#107]
Need a simple HTTP endpoint that takes one parameter `username` and returns `{ ok: true, available: true }` if the username is available (doesn't already exist) or `{ ok: true, available: false }` if it's already been taken.

**Comment by chrishein3** [comment]
Do you want new endpoint besides `/process` endpoint or add new schema like `https://schema.org/Person/Search`?

**Comment by chrishein3** [comment]
if `ok` is not `true`, this mean some unhandled error occur, don't take serious to `available` field. Http StatusCode must be 200 and `available` field must be `true`.
