### ISSUE TITLE
Community memberships - joining/leaving

### ISSUE THREAD

**Issue by Entryist** [getZION/relay#71]
Need to figure out how to represent joining and leaving communities in the database, and what app-facing endpoint to use for this (`hub.Process` or something else).

Perhaps can use a standard pivot table `user_communities`.

May or may not make sense to do this via Identity Hub, at least in the short term. @chrishein3 you can decide how to handle this.

App API calls: https://github.com/getZION/use-zion/wiki/API-spec#community-profile

**Comment by chrishein3** [comment]
```
JoinCommunity
	Join - CollectionsWrite
	Where schema is needed, use "https://schema.org/JoinAction"
	
LeaveCommunity
	Leave - CollectionsWrite
	Where schema is needed, use "https://schema.org/LeaveAction"
```

Also with the Data property you need to send me `UserId` and `CommunityId`.
Other Identity Hub Methods will do nothing for these actions.

**Comment by chrishein3** [comment]
You need to send me `Data` property showed as below;
```json
{  
       "user_id": 1, 
       "community_id": 1 
}
````

Join Operation Example:
```shell
grpcurl -d '{ "requestId": "d82c0026-ed42-4b26-81f3-94805958a75c", "target": "test", "messages": [ { "data": "{ \"user_id\": 1, \"community_id\": 1 }", "descriptor": { "method": "CollectionsWrite", "schema": "https://schema.org/JoinAction", "dateCreated": "10", "objectId": "d82c0026-ed42-4b26-81f3-94805958a75c" } } ]}' \
  -plaintext \
  localhost:9990 proto.identityhub.v1.HubRequestService/Process
```

Leave Operation Example:
```shell
grpcurl -d '{ "requestId": "d82c0026-ed42-4b26-81f3-94805958a75c", "target": "test", "messages": [ { "data": "{ \"user_id\": 1, \"community_id\": 1 }", "descriptor": { "method": "CollectionsWrite", "schema": "https://schema.org/LeaveAction", "dateCreated": "10", "objectId": "d82c0026-ed42-4b26-81f3-94805958a75c" } } ]}' \
  -plaintext \
  localhost:9990 proto.identityhub.v1.HubRequestService/Process
```

I don't keep to extra properties like `created` (joinedDate), `leaved` (record directly removed from DB) etc ... But if it's needed, we need to create some `audit_logs` table.
