### ISSUE TITLE
Use did/zid not id in community membership schema 

### ISSUE THREAD

**Issue by Entryist** [getZION/relay#77]
We can't assume all community members will use the same relay, so we can't use the auto-generated `id` field to track community membership. Instead need to use `did` for users and `zid` for communities, both of which are the only globally unique identifiers for user and community.

See the [Notes on data models](https://github.com/getZION/relay/wiki/Notes-on-data-models#types-of-ids) section on different IDs used in Zion.

**Comment by chrishein3** [comment]
```json
{ "community_zid": "test_zid", "user_did": "test_did" }
```

You need to send `community_zid` and `user_did` when join or leave the community.
