### ISSUE TITLE
Support image uploads for CollectionsWrite

### ISSUE THREAD

**Issue by Entryist** [getZION/relay#78]
We need to handle image uploads for the following Zion models:
- [Message](https://github.com/getZION/relay/blob/main/docs/grpc-zion.md#proto.zion.v1.Message) - `img` field
- [Community](https://github.com/getZION/relay/blob/main/docs/grpc-zion.md#community) - `img` field
- [User](https://github.com/getZION/relay/blob/main/docs/grpc-zion.md#user) - `picture` field (and let's rename this to `img` if not too difficult)

User will send image in whatever format is typical for React Native to Go image uploads.

Relay needs to save it to an S3 storage bucket tied to that user and save the HTTP link in the `img` field.

A similar setup will be needed to handle the Message field `video`, but we'll wait til April to handle video.

**Comment by Entryist** [comment]
@mohamedsamara can figure out what's needed on the client side re React Native image uploads

**Comment by Entryist** [comment]
Clarifying that the images need to be uploaded from the app to relay and then to S3, not directly from app to S3.

Conceivably images could be uploaded to S3 directly from React Native, bypassing the server entirely, but that will not work for our use case where we rely on relay for validation and handling payments associated with messages.

**Comment by chrishein3** [comment]
Related UI feature: https://github.com/getZION/v2/pull/60
