### ISSUE TITLE
CollectionsQuery: Community - missing fields

### ISSUE THREAD

**Issue by Entryist** [getZION/relay#89]
Getting the below Community response object. Need to also send to client:
- `img` (if there is one -- in the case below, there is an img in the database entry but it's not being returned in the response)
- `created`
- `lastActive`
- `public`

![missing](https://user-images.githubusercontent.com/14167547/159984560-0ed858e2-b674-4398-af13-bc214d9fb295.png)

**Comment by Entryist** [comment]
Also missing `zid`

**Comment by chrishein3** [comment]
> Also missing `zid`

All missing fields added.
