### ISSUE TITLE
Add joinedDate/leftDate to Community

### ISSUE THREAD

**Issue by Entryist** [getZION/relay#92]
We want to be able to show activity notifications like "Joe joined X community" and "Sarah left Y community", so we need to track joined+leaving dates.

Also need to revise "leaving community" action to not delete the relationship entry, instead just add leftDate

**Comment by chrishein3** [comment]
if we don't delete to entry when user `leave community`; 
**Scenario**
`Joe joined X Community` -> `Joe left X Community` -> `Joe joined X Community`

Pivot table build relationship with `CommunityZid` and `UserDid`. In this scenario they still have same values (zid, did) and record isn't deleted when user leave. So I cannot create new record when user joined again.

**Solutions**
- Basically I can change pivot table structure like;
       `ID (uuid, need to be unique all Zion)`, `CommunityZid (zid)`, `UserDid (Did)`, `JoinedDate (date)`, `LeavedDate (date)`
       But in this case, `ID` might be different for other relays.
- We can create new table named something like `CommunityAudits` (_contains much more work but consistent_);
      `ID (uuid, just for primary key)`, `event_name (string)`, `event_date (date)`, `user_did (did)`
      Maybe we can create table specifically for `Communities` or for all the every event happened inside system. But need to 
      store be same data for all relays.

**Comment by Entryist** [comment]
The first solution there looks fine for now
