### ISSUE TITLE
Community owner can remove member 

### ISSUE THREAD

**Issue by Entryist** [getZION/relay#96]
Owner of a community needs to be able to remove a member from their community.

**Comment by chrishein3** [comment]
Do we need to some additional field something like `left_reason` to `community_user` table? For example; if user left by own decision, reason can be `NULL`, if kicked by community, reason can be `kicked by Owner`

**Comment by Entryist** [comment]
Yes let's do that

**Comment by chrishein3** [comment]
```shell
grpcurl -d '{ "requestId": "3eb8ea70-7ea5-4069-a153-cfb0ea682df9", "target": "test", "messages": [ { "descriptor": { "method": "CollectionsWrite", "schema": "https://schema.org/Organization/KickUser", "dateCreated": "10", "objectId": "d82c0026-ed42-4b26-81f3-94805958a75c" }, "data": "{ \"user_did\": \"did1\", \"community_zid\": \"b20f7f0d-7cdb-4693-8028-d2c3cb82bec4\" }" } ] }' \
	-plaintext \
	localhost:9990 proto.identityhub.v1.HubRequestService/Process
```

You can see example gRPC request above. 
You need to use `https://schema.org/Organization/KickUser` as schema (maybe we can discuss to change schema) and `{ \"user_did\": \"did1\", \"community_zid\": \"b20f7f0d-7cdb-4693-8028-d2c3cb82bec4\" }` as data.
